### ISSUE TITLE
Xiaomi Air Conditioning Companion2集成添加多个设备只有一个可用

### ISSUE THREAD

**Issue by oliver-ok** [EugeneLiu/xiaomi_airconditioningcompanionMCN02#23]
Xiaomi Air Conditioning Companion 2集成，配置米家空调伴侣2代
configuration.yaml文件配置如下：

```
climate:   
    platform: xiaomi_miio_airconditioningcompanionmcn02
    name: A空调
    host: 192.168.1.157
    token: A空调的token
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60

    name: B空调
    host: 192.168.1.205
    token: B空调的token
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60
   
    name: C空调
    host: 192.168.1.162
    token: C空调的token
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60
```

以上配置，只有放在最后的空调可以生效，放在前面的实体显示不可用。例如以上的配置，只有C空调可用，A和B不可用，如果A空调放在最后则只有A空调可用。

以上配置哪里语法错误呢？反复尝试都找不到方法。感谢指点！
